---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Log into the Web Console
    - name: module-02
      label: View metrics and history
    - name: module-03
      label: Generate a CPU-hot workload
    - name: module-04
      label: CPU performance at-a-glance
tabs:
   - name: ">_ Terminal"
    port: 443
    path: /tty1
    user: root
    host: rhel
